// This file is auto-generated by @hey-api/openapi-ts

export type GetHelloData = {
    body?: never;
    path?: never;
    query?: {
        name?: string;
    };
    url: '/hello';
};

export type GetHelloResponses = {
    /**
     * Everything went ok I guess
     */
    200: string;
};

export type GetHelloResponse = GetHelloResponses[keyof GetHelloResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};